export const apiAccommodationTypes = 'accommodation-types'
export const apiCalendarPresets = 'calendar-presets'
export const apiThematic = 'thematic'
export const apiVariables = 'variables'
export const apiDestination = 'destinations'
