export const baseApiUrl = 'https://travello-tour-backend-7b2f.twc1.net/'
export const apiAccommodationTypes = 'accommodation-types'
export const apiCalendarPresets = 'calendar-presets'
export const apiThematic = 'thematic'
export const apiVariables = 'variables'
export const apiDestination = 'destinations'
export const apiAuth = 'auth'
